services:
  - type: web
    name: warranty-wallet-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATA_MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: ALLOWED_ORIGINS
        sync: false
